### ISSUE TITLE
Can't build genzehn

### ISSUE THREAD

**Issue by nbenm** [ndless-nspire/Ndless#150]
```
make all in genzehn...
make[3] : on entre dans le répertoire « /usr/local/Ndless/ndless-sdk/tools/genzehn »
g++ -Wall -Wextra -std=c++11 -I elfio-3.2 genzehn.cpp -lboost_program_options -lz -o ../../bin/genzehn || g++ -Wall -Wextra -std=c++11 -I elfio-3.2 genzehn.cpp -lboost_program_options-mt -lz -o ../../bin/genzehn
genzehn.cpp:8:10: fatal error: boost/program_options.hpp: No such file or directory
 #include <boost/program_options.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
genzehn.cpp:8:10: fatal error: boost/program_options.hpp: No such file or directory
 #include <boost/program_options.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [Makefile:4: ../../bin/genzehn] Error 1
make[3] : on quitte le répertoire « /usr/local/Ndless/ndless-sdk/tools/genzehn »
make[2]: *** [Makefile:4: all] Error 1
make[2] : on quitte le répertoire « /usr/local/Ndless/ndless-sdk/tools »
make[1]: *** [Makefile:14: build-tools] Error 2
make[1] : on quitte le répertoire « /usr/local/Ndless/ndless-sdk »
make: *** [Makefile:19: build-ndless-sdk] Error 2
```

```
port content boost|grep program_options.hpp
  /opt/local/include/boost/program_options.hpp
```

I'm stuck here. Please help.
It's really a pain to build Ndless on a Mac.

**Comment by adriweb** [comment]
It's really only a pain if you use macports (basically outdated) instead of brew (not outdated). I haven't used macports in many many years and I don't miss it :D

Anyway, it seems it's just a `-I/opt/local/include` flag somewhere since the error message says it can't find the header. Those `/opt` aren't quite "standard"/"default" I suppose, contrary to `/usr/local` which is what brew uses. I guess this is why you also had to mess with your path more than usually needed.
So, try to add that -I in the makefile

**Comment by nbenm** [comment]
@adriweb 

> it seems it's just a -I/opt/local/include flag somewhere since the error message says it can't find the header

I have already tried this. But maybe in a wrong way. I'll try again.

I'll also have a look at brew...
It was much easier on a Linux box.

**Comment by adriweb** [comment]
OK.
FWIW, once the deps are installed with brew, I believe I didn't have anything to change to build on mac.

**Comment by nbenm** [comment]
I've installed brew, and things go better. I can run a HelloWorld on a TI Nspire CX CAS device.
Thanks @adriweb 
I have now to install and check all my usual stuff.
