### ISSUE TITLE
Add nspire target file

### ISSUE THREAD

**Issue by lights0123** [ndless-nspire/Ndless#155]
In my project to add Rust support for Ndless, I need to store a target file somewhere, which tells `rustc` and LLVM about the CPU and environment of the Nspire. Is it possible to add this file to a constant path, such as ~/.ndless/armv5te-nspire-eabi.json?

```json
{
    "arch": "arm",
    "cpu": "arm926ej-s",
    "data-layout": "e-m:e-p:32:32-i64:64-v128:64:128-a:0:32-n32-S64",
    "llvm-target": "armv5te-none-eabi",
    "os": "linux",
    "vendor": "unknown",
    "relocation-model": "pic",
    "target-endian": "little",
    "target-env": "newlib",
    "target-pointer-width": "32",
    "target-c-int-width": "32",
    "exe-allocation-crate": "alloc_system",
    "lib-allocation-crate": "alloc_system",
    "linker": "nspire-gcc",
    "linker-flavor": "gcc",
    "ar": "arm-none-eabi-ar",
    "dynamic-linking": false,
    "executables": true,
    "features": "+v5te,+soft-float,+strict-align",
    "c-compiler": "arm-none-eabi-gcc",
    "c-flags": "-mcpu=arm926ej-s -D _TINSPIRE -fuse-ld=gold",
    "c-link-flags": "-mcpu=arm926ej-s -D _TINSPIRE -fuse-ld=gold",
    "c-triple": "arm-none-eabi"
}
```

**Comment by FrostyPenguin** [comment]
I'm no rust developer (nor do I use LLVM), but what about just creating this file? I see no problem if you have proper access rights to `~/.ndless`. :smile:

If you want this file to be added to Ndless' source code, however, please open a pull request. But again, the only target files I ever wrote were cross files for Meson and I'm no maintainer of this project. I'm sure if you open a pull request that is adding this file, someone official will be able to tell you more about this.

**Comment by lights0123** [comment]
If this file is added, then no other ndless- specific dependencies will be required to use it. I opened an issue because there is no current system for installing files to that directory, and I didn't know if there was a preferred way to modify the install script.

**Comment by FrostyPenguin** [comment]
AFAIK, the current model is that all files remain in the cloned Ndless directory.

Note that (to my knowledge) `~/.ndless` is primarily used for installing static libraries. Therefore, it is created by `nspire-gcc`. The new use would, as you said, require an update of a build file, but as this is a pretty new approach (for Ndless) we will have to ask a maintainer.

I would say that this installation should be added to build_toolchain.sh as:
  * plain `make` doesn't install anything in the UN*X world (`make install` would)
  * `make` might be used to test and develop the toolchain (like genzehn). Installing the file every time someone calls `make` would be nuts.

Now that we've clarified what this issue is for (at least it's more clear for me now), we might be able to tag @Vogtinator to kindly ask for his opinion :sunglasses:

**Comment by Vogtinator** [comment]
Does it need to be in a fixed location? The path to the ndless-sdk directory is available by running `nspire-tools path`.

**Comment by lights0123** [comment]
Closing this issue as I have decided that my current way of doing it is probably the best solution.
