### ISSUE TITLE
ndless for TI-nspire cx cas

### ISSUE THREAD

**Issue by smuranjan1** [ndless-nspire/Ndless#187]
I currently have a TI-nspire cx cas running on version 4.5.0.1180 with ndless version 4.5.0. I downloaded version 0.92 of gbc4nspire and when I launch it, it says, "Activating compatibility mode. This application hasn't been updated to work with your hardware. You may run into issues!" It then loads the emulator while displaying the documents menu on top and then shortly after crashes. Do any of you know what is causing this and how to fix it?

**Comment by KhiemmyT** [comment]
You will need to download version 0.93 of gbc4nspire here, it supports the newer calculators that you have with a modified display:
https://tiplanet.org/forum/archives_voir.php?id=1649

Since your calculator is new, ndless will have problems running some .tns files since Texas Instruments used a different display which pretty much screws up the apps. You'll have to buy an older model of a ti nspire from eBay or some other online place if you want to avoid these problems.

**Comment by smuranjan1** [comment]
OK thank you!

**Comment by Vogtinator** [comment]
Not an issue in Ndless, closing.
