### ISSUE TITLE
msleep doesn't work

### ISSUE THREAD

**Issue by lights0123** [ndless-nspire/Ndless#207]
`msleep` does nothing on Firebird (I haven't tested this on hardware):
```cpp
#include <os.h>

int main(void) {
	show_msgbox("Title", "msg");
	msleep(1000);
	show_msgbox("Title2", "msg");
}
```
This has no pause between message boxes. I'm on commit 9ad392aca8.

**Comment by Vogtinator** [comment]
`msleep` uses the timer in one-shot mode and writes the count to the load register and then immediately waits for the value to reach 0.

https://github.com/ndless-nspire/Ndless/blob/9ad392aca8874412f69492cf67d216efc3f62415/ndless-sdk/libndls/sleep.c#L49-L51

The issue is that on firebird, writes to the load register only reach the value on the next "tick", so if the timer had a value of 0 already, that's read and the loop doesn't even make a single iteration.

According to the SP804 datasheet

> After a load operation has taken place by writing a new load value to TimerXLoad, the
> TimerXValue register reflects the new load value immediately in the PCLK clock
> domain without waiting for the next TIMCLK edge qualified by TIMCLKENX.

Which sounds to be like writes to load are reflected in the value register immediately. Doing it like that in Firebird makes the example work just fine.

Question is whether the hardware agrees.

**Comment by lights0123** [comment]
> doing it like that in Firebird

What is "that" referring to? I'm able to make it work by either calling `idle()` before the `while` loop or converting it to a do-while loop (`do idle(); while(*value > 0);`), but that has the side effect of waiting for the next interrupt if `0` is passed to the function.

**Comment by Vogtinator** [comment]
If it `msleep` works as-is on hardware, it's a bug in firebird that is easily fixed. If not, I'd convert `msleep` to use the interrupt status bit of the timer instead.

**Comment by Vogtinator** [comment]
Ok, the hardware does not behave like that, writes to the load register are not immediately visible in the value one.
However, `msleep` works fine, as the `value` register is in none of my tries actually 0.
After `show_msgbox` the timer is in periodic mode with a reload of 20, which means that the theoretical propability of the value being 0 there is 1/21. It's not actually clear to me whether the value of `0` is actually ever visible or whether the decrementing of the counter triggers a reload before the interrupt is processed. That's what has to be checked on hardware next.

**Comment by Vogtinator** [comment]
> It's not actually clear to me whether the value of 0 is actually ever visible or whether the decrementing of the counter triggers a reload before the interrupt is processed. That's what has to be checked on hardware next.

0 is visible, so this is a bug in libndls.

**Comment by Vogtinator** [comment]
^ works in firebird and on HW, feel free to test.
