### ISSUE TITLE
Nover and nsNandMgr not working on Ndless 5.2

### ISSUE THREAD

**Issue by MLGityaJtotheA** [ndless-nspire/Ndless#245]
When I try to run Nover, the screen freezes and I have to restart the calc to get out. It's always the same outcome no matter how many times I run it.

As with nsNandMgr (which I'm using to get the necessary files to emulate the calc on my phone), for a moment the loading screen does show saying 'Refreshing' but after that, the calc immediately restarts. Tried running it multiple times as well.

**Comment by adriweb** [comment]
Do not try Nover on the CX II ; not only is the hardware different (and with a much faster CPU already, making overclocking basically unnecessary), but also Nover hasn't been updated to work for the new software/hardware.

That said your message is confusing: you say 5.2 (implying a CX II), but you also mention emulation (implying CX, since CX II emulation isn't publicly possible yet). What do you have? Nover is expected to work on a CX with OS 4.5.3 + Ndless, although I'm not sure if anyone tried it.

**Comment by adriweb** [comment]
Tagging @critor just in case.

**Comment by MLGityaJtotheA** [comment]
> Do not try Nover on the CX II ; not only is the hardware different (and with a much faster CPU already, making overclocking basically unnecessary), but also Nover hasn't been updated to work for the new software/hardware.

Ok gotcha

> That said your message is confusing: you say 5.2 (implying a CX II), but you also mention emulation (implying CX, since CX II emulation isn't publicly possible yet). What do you have?

oh. I assumed that if I used polydumper (I meant that instead of nsNandMgr oops), it would give me the boot images like normal. I guess not 😅

> Nover is expected to work on a CX with OS 4.5.3 + Ndless, although I'm not sure if anyone tried it.

I can confirm that it does work. I actually have two calcs, one a regular CX and the other a new CX II. It's the CX II that's having issues obviously, the regular CX is working fine on ndless 4.3.14. I have a question regarding that actually: why is OS 4.3.14 not on the official TI sites? I don't understand the explanation on the ndless site...

**Comment by adriweb** [comment]
OS 4.5.3 is actually on TI's website (that's how it was obtained after all :p), just not extremely put forward instead of 4.5.2 for some reason.

**Comment by Danke-Boi** [comment]
I would love to overclock my cx 2, I hope they develop a new nover for it.
Because maybe ps1 emulation might be possible? It’s a 33.8688 MHz
processor, and the cx 2 has a clock speed of 396 MHz. Or, if we get it
really up there with overclocking, like 20% increase, n64 games? I’m just
wondering what kind of power it would take to emulate this stuff. If I
would get into c++ or c or python, I would shoot for one of those consoles,
or the gba.

**Comment by adriweb** [comment]
Well GBA is already emulated with gpsp, running at full speed on the CX II.

For other consoles, see this: https://tiplanet.org/forum/viewtopic.php?f=20&t=17762

**Comment by Danke-Boi** [comment]
Do you think the n64 could be emulated? It’d be hard to play with only a
trackpad, but it could work.

**Comment by Facts-and-Logic** [comment]
N64 is a 64 bit console while the TI Nspire has a 32 bit processor. It could theoretically be emulated albeit at a very slow speed compared to 32 bit game emulation on 32 bit hardware like the GBA. Also, you'll need to find a developer who would put a lot of time in programming it.

**Comment by adriweb** [comment]
That said, it wouldn't be the first 64bit console to be emulated on the Nspire ; the Jaguar was: https://tiplanet.org/forum/viewtopic.php?t=19354

**Comment by Vogtinator** [comment]
Closing as this is not an issue with Ndless.
