### ISSUE TITLE
touchpad not working in minivmac

### ISSUE THREAD

**Issue by chenxi050402** [ndless-nspire/Ndless#250]
I opened up minivmac and found the touchpad not working, except the middle button, and I couldn't find anywhere to ask.

**Comment by Vogtinator** [comment]
Apparently it uses the relative values from the touchpad, which weren't implemented in the compat mode. Please try this:
[ndless_resources.zip](https://github.com/ndless-nspire/Ndless/files/5410459/ndless_resources.zip)

Unfortunately I can't quite get it working in firebird, and so I'm unable to test this myself.

**Comment by chenxi050402** [comment]
> Apparently it uses the relative values from the touchpad, which weren't implemented in the compat mode. Please try this:
> [ndless_resources.zip](https://github.com/ndless-nspire/Ndless/files/5410459/ndless_resources.zip)
> 
> Unfortunately I can't quite get it working in firebird, and so I'm unable to test this myself.

It works now! Thanks!

**Comment by Vogtinator** [comment]
I debugged why the cursor didn't work in Firebird. It turns out to be a bug in the modified `SDL_tinspireevents.c` file which it needs for cursor support: `touchpad_scan` causes the relative X/Y values to reset (the touchpad does that on each read of those values), so it has to make sure to use the values from the first call for event handling. However, it calls `isKeyPressed` for arrow keys first, so it lost most of the movement data. With this function instead it works much better, but also way too fast now:

```
void NSP_PumpEvents(_THIS)
{
       nsp_update_mouse();
       nsp_update_mouse_click();

       nsp_update_keyboard();
       nsp_update_arrow_keys();
}
```

With this I could confirm that the patch for ndless indeed works as expected.

**Comment by Vogtinator** [comment]
I rebuilt minivmac with the current toolchain and a newer version of nSDL (needed a fix for 8bpp, https://github.com/Vogtinator/nSDL/pull/1), please try:

[minivmac.zip](https://github.com/ndless-nspire/Ndless/files/5418719/minivmac.zip)

**Comment by unilock** [comment]
@Vogtinator At least on my calculator (P-0615V), the cursor is now actually usable in minivmac, so thanks for that!
Unfortunately, with your new version, it seems it's no longer possible to use the numpad as a mouse ("tab", the button meant to switch between using the touchpad or numpad as a mouse, does nothing), meaning you can't hold down click while moving the mouse, and thus can't use menu items in System 7.
Would it be possible to reassign, say, the "scratchpad" button to function as click? This would also make any code that relies on the numpad being used for mouse functions redundant, I'd imagine.

**Comment by Vogtinator** [comment]
That doesn't seem to work for me with the original version either, maybe you're using a different version?

Apparently this is because the nspire's numeric keys don't map to the numpad keys. I changed that and it appears to work, though very slowly: [minivmac_1.zip](https://github.com/ndless-nspire/Ndless/files/5424408/minivmac_1.zip)

**Comment by Vogtinator** [comment]
> Would it be possible to reassign, say, the "scratchpad" button to function as click? This would also make any code that relies on the numpad being used for mouse functions redundant, I'd imagine.

Done: [minivmac_2.zip](https://github.com/ndless-nspire/Ndless/files/5424450/minivmac_2.zip)

**Comment by unilock** [comment]
@Vogtinator The version I was originally using can be found [here](https://tiplanet.org/forum/archives_voir.php?id=12534). Apparently, "Mouse Keys" is a feature of Mac OS itself rather than the emulator; the "tab" key is simply a shortcut for the key combination "Command-Shift-Clear", which enables "Mouse Keys".
I can't tell whether "Mouse Keys" is working better with your updated version, or if I just wasn't holding down the number keys long enough in the original version. Either way, it's a bit moot, as using the "scratchpad" key as click works quite well. Thank you!

**Comment by Vogtinator** [comment]
FTR, the nSDL modifications for that are in the `for-minivmac` branch: https://github.com/Vogtinator/nSDL/tree/for-minivmac

**Comment by chenxi050402** [comment]
> > Would it be possible to reassign, say, the "scratchpad" button to function as click? This would also make any code that relies on the numpad being used for mouse functions redundant, I'd imagine.
> 
> Done: [minivmac_2.zip](https://github.com/ndless-nspire/Ndless/files/5424450/minivmac_2.zip)

It stops working after a while (freezing when booting up)
