### ISSUE TITLE
Timers

### ISSUE THREAD

**Issue by rayzerbrain** [ndless-nspire/Ndless#380]
Is there a way to use the timers utilized in msleep to time frames, i.e. increment a value every x milliseconds? I tried using the sdl_timer but it says there's no thread support.  

If you could at least point me to some documentation I'd appreciate it, the link given in the msleep definiton seems to be outdated.

**Comment by Vogtinator** [comment]
What's the specific use case you need this for?

What you can do is instead of reading that particular value, read the elapsed timer from a timer value register and divide that by the granularity you want counted. For that you'll have to write to the HW specific timer registers like libndls does.

> If you could at least point me to some documentation I'd appreciate it, the link given in the msleep definiton seems to be outdated.

It just links to the datasheet for the SP804 timer module, you can find that athttps://developer.arm.com/documentation/ddi0271/d/.

**Comment by rayzerbrain** [comment]
Thank you- the documentation was enough to help me
