### ISSUE TITLE
mkStubs.php can't find arm-none-eabi-g++

### ISSUE THREAD

**Issue by QuaternionsRock** [ndless-nspire/Ndless#71]
```
Quaternions-MacBook-Pro:Ndless quaternionsrock$ make
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ndless-sdk
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C libsyscalls
php mkStubs.php > ../include/syscall-decls.h
arm-none-eabi-g++ -mcpu=arm926ej-s -std=c++11 -nostdlib -O3 -fPIE -fno-exceptions -fno-rtti -mlong-calls -Wall -Werror -I ../include/ -I ../thirdparty/nspire-io/include/ -D_TINSPIRE -ffunction-sections -fdata-sections -c stubs.cpp -o stubs.o
make[2]: arm-none-eabi-g++: No such file or directory
make[2]: *** [stubs.o] Error 1
make[1]: *** [build-libsyscalls] Error 2
make: *** [build-ndless-sdk] Error 2
```

What's this about?

**Comment by Legimet** [comment]
You have to install the toolchain and add it to your PATH. Look at ndless-sdk/
toolchain/build_toolchain.sh

**Comment by QuaternionsRock** [comment]
@Legimet after spending the last two hours discovering multiple layers of dependencies required to run a simple script, I have decided to abandon the project. Worst makefile I've ever seen

**Comment by adriweb** [comment]
I don't know what's hard to understand/do, it's all on the wiki...
- install the few deps (in your case, with brew)
- clone the repo
- launch build_toolchain.sh
- run the makefiles

Works perfectly fine for me on macOS as well. Especially since I automated some toolchain steps that required manual adjustements for mac, some weeks ago. It's all done automatically now.

**Comment by QuaternionsRock** [comment]
@adriweb aaaaaand I was installing each dependency manually. God damnit 📦
