### ISSUE TITLE
Ndless-sdk:  "nspire-gcc: Command not found"

### ISSUE THREAD

**Issue by s1brito** [ndless-nspire/Ndless#83]
Hello
Can anyone help me on this?
I keep getting this error:
"nspire-gcc: Command not found"

![image](https://user-images.githubusercontent.com/32426642/31051732-5c5327d6-a668-11e7-80bf-c4f69f19e08f.png)

Thank you
sb

**Comment by Vogtinator** [comment]
Did you follow all the steps for setting up the SDK? Did you set $PATH correctly after building the toolchain?

**Comment by s1brito** [comment]
Good morning

I've repeated all the process again and this is the output:
5 cd toolchain
brito@DESKTOP-OLM91)D /cygdrive/c/ndless-master/ndless-sdk/toolchain
./build_toolchain.sh
Building and installing to '/cygdrive/c/ndless-master/ndless-sdk/toolchain/insta
Building Binutils...
Building GCC (step 1)...
Building Newlib...
Building GCC (step 2)...
Building GDB...
Done!
Don't forget to add '/cygdrive/c/ndless-master/ndless-sdk/toolchain/install/bin'
to your SPATH along with /cygdrive/c/ndless-master/ndless-sdk/toolchain/../bin.
brito@DESKTOP-OLM9171) /cygdrive/c/ndless-master/ndless-sdk/toolchain
5 export PATH="c:/ndless-master/ndless-sdk/toolchain/install/bin:c:/ndless-maste
r/ndless-sdk/toolchain/../bin:5{PATH}"
brito@DESKTOP-OLM9130 /cygdrive/c/ndless-master/ndless-sdk/toolchain
make
make: *** No targets specified and no makefile found. Stop.
brito@DESKTOP-OLM913D /cygdrive/c/ndless-master/ndless-sdk/toolchain
5 cd..
-bash: cd..: command not found
brito@DESKTOP-OLM917D /cygdrive/c/ndless-master/ndless-sdk/toolchain
5 cd..
-bash: cd..: command not found
brito@DESKTOP-OLM91)D /cygdrive/c/ndless-master/ndless-sdk/toolchain
5 cd
brito@DESKTOP-OLM91JD /cygdrive/c/ndless-master/ndless-sdk
5 make
make -C libsyscalls
make[1]: Entering directory '/cygdrive/c/ndless-master/ndless-sdk/libsyscalls'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/cygdrive/c/ndless-master/ndless-sdk/libsyscalls'
make -C libndls
make[1]: Entering directory '/cygdrive/c/ndless-master/ndless-sdk/libndls'
nspire-gcc -02 -funroll-loops -nostdlib -Wall -Werror -Wextra -ffunction-section
s -fdata-sections -c wait_key_pressed.c
make[1]: nspire-gcc: Command not found
make[1]: *** [Makefile:18: wait_key_pressed.o] Error 127
make[1]: Leaving directory 7cygdrive/c/ndless-master/ndless-sdk/libndls'
make: *** [Makefile:14: build-libndls] Error 2
brito@DESKTOP-OLM91)D /cygdrive/c/ndless-master/ndless-sdk
echo "SPATH"
c:/ndless-master/ndless-sdk/toolchain/install/bin:c:/ndless-master/ndless-sdk/toolchain/../bin:/usr/local/bin:/usr/bin:/cygdrive/c/Program Files (x86)/Cuminas/Document Express DjVu Plug -in:/cygdrive/c/ProgramData/Oracle/lava/javapath:/cygdrive/c/WINDOWS/system32:/cygdriv
e/c/WINDOWS:/cygdrive/c/WINDOWS/System32/Wbem:/cygdrive/c/WINDOWS/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files/Calibre2:/cygdrive/c/Program Files (x86)/Skype/Phone:/cygdrive/c/Program Files/MATLAB/R2015b/runtime/win64:/cygdrive/c/Program Files/MATLAB/R2015b/
bin:/cygdrive/c/Program Files/MATLAB/R2015b/polyspace/bin:/cygdrive/c/Program Files (x86)/Pinnacle/Shared Files:/cygdrive/c/Program Files (x86)/Lua/5.1:/cygdrive/c/Program Files (x86)/Lua/5.1/clibs:/cygdrive/c/Program Files/SDCC/bin:/cygdrive/c/Users/brito/AppData/Local/
Microsoft/WindowsApps:/usr/lib/lapack

Thank you for your help
sb

**Comment by Vogtinator** [comment]
Why did you replace ```/cygdrive/c``` with ```c:/```? That's wrong.

**Comment by adriweb** [comment]
Also “5” instead of “$” in the path export command.

**Comment by s1brito** [comment]
Because I'm a rookiee, ehehe This is my first time in this field...
I changed what you've said and it works but another error came up.
Nevertheless nspire-gcc is running. It's a critical error or not?
![image](https://user-images.githubusercontent.com/32426642/31053747-380ed6de-a69c-11e7-83d6-4b6ef0794e9e.png)

**Comment by s1brito** [comment]
the "5" instead of $ is an error of the pdf ocr...

**Comment by Vogtinator** [comment]
I see the directory is called ```ndless-master```, which means you did not git clone the repo but instead downloaded it as archive and extracted it. That won't work, if you still have the ".gitmodules" file in ndless-master you can run ```git submodule init; git submodule update``` to remedy that. You should still replace ndless-master with a full git checkout though to be able to receive updates. You can simply copy over the toolchain directory to the new checkout to avoid rebuilding the toolchain.

**Comment by s1brito** [comment]
Hello
So I decided to start all over again.
1 - Installed the Cygwin with all the dependencies
2 - Installed GitHub Desktop
3 - Did a Git clone of the repo

The build_toolchain.sh was not working so I've copied the files in the Nless-master similar directory and overwrited them.
I added the folders to the PATH

![image](https://user-images.githubusercontent.com/32426642/31076526-74d89ff6-a772-11e7-8652-420ed575fd82.png)

Do you have any idea why this isn't working?

Thank you very much

**Comment by adriweb** [comment]
Yeah, it's a simple windows-related issue IIRC. I think using dos2unix on the bin folder fixes that. See #27 and #41 (people had the same issue, although on different paths, but the solution is the same)

**Comment by Vogtinator** [comment]
I have the suspicion that the github windows client mangles the files as it doesn't open them with the binary flag. It might work if you use git clone within cygwin, which you should do anyway (the github desktop application is awful)

**Comment by Legimet** [comment]
Wow that really is awful. It's best just to learn how to use git on the command line.

**Comment by GitHubQuestionAsker** [comment]
Hello, I'm having the same problem trying to compile a program written to work with Ndless, whenever I run the Makerfile, Im told nspire-gcc: command not found. Here is the Makerfile, `GCC = nspire-gcc
LD = nspire-ld
GCCFLAGS = -O2 -Wall -W -marm
LDFLAGS = 
OBJCOPY := "$(shell which arm-elf-objcopy 2>/dev/null)"
ifeq (${OBJCOPY},"")
	OBJCOPY := arm-none-eabi-objcopy
endif
EXE = hide.tns
OBJS = hide.o
DISTDIR = ..
vpath %.tns $(DISTDIR)

all: $(EXE)

%.o: %.c
	$(GCC) $(GCCFLAGS) -c $<

$(EXE): $(OBJS)
	$(LD) $(LDFLAGS) $^ -o $(@:.tns=.elf)
	mkdir -p $(DISTDIR)
	$(OBJCOPY) -O binary $(@:.tns=.elf) $(DISTDIR)/$@

clean:
	rm -f *.o *.elf *~
#	rm -f $(DISTDIR)/$(EXE)`
I figure that I need to reference nspire-gcc to a file or something in the Ndless SDK but I dont know where that could be found.

**Comment by adriweb** [comment]
Well, literally look at the answers above

**Comment by GitHubQuestionAsker** [comment]
> 
> 
> Well, literally look at the answers above

I may be mistaken but the topics above talk about an incorrect cloning process and problems with the $PATH with the SDK, my problem is about incorporating functions from the SDK into a 3rd-party program.

**Comment by GitHubQuestionAsker** [comment]
After setting up my $PATH properly (thank you for the help @adriweb ) I'm receiving an error about one of the SDK files, but I believe that the SDK is perfectly fine because I've compiled things with it before without a problem
`$ make
nspire-gcc -O2 -Wall -W -marm -c hide.c
hide.c: In function ‘setPixel’:
hide.c:60:8: warning: implicit declaration of function ‘lcd_isincolor’ [-Wimplic                                                                                                                it-function-declaration]
     if(lcd_isincolor()) {
        ^~~~~~~~~~~~~
In file included from /home/littl/Ndless/ndless-sdk/include/os.h:24:0,
                 from hide.c:3:
/home/littl/Ndless/ndless-sdk/include/libndls.h:163:95: error: expected ‘;’ befo                                                                                                                re ‘}’ token
  #define SCREEN_BASE_ADDRESS ({"SCREEN_BASE_ADDRESS got removed in favor of the                                                                                                                 lcd_blit API."})
                                                                                                                                                                                                               ^
hide.c:61:47: note: in expansion of macro ‘SCREEN_BASE_ADDRESS’
         unsigned short* p = (unsigned short*)(SCREEN_BASE_ADDRESS + (x << 1) +                                                                                                                 (y << 9) + (y << 7));
                                               ^~~~~~~~~~~~~~~~~~~
/home/littl/Ndless/ndless-sdk/include/libndls.h:163:95: error: expected ‘;’ befo                                                                                                                re ‘}’ token
  #define SCREEN_BASE_ADDRESS ({"SCREEN_BASE_ADDRESS got removed in favor of the                                                                                                                 lcd_blit API."})
                                                                                                                                                                                                               ^
hide.c:65:45: note: in expansion of macro ‘SCREEN_BASE_ADDRESS’
         unsigned char* p = (unsigned char*)(SCREEN_BASE_ADDRESS  + ((x >> 1) +                                                                                                                 (y << 7) + (y << 5)));
                                             ^~~~~~~~~~~~~~~~~~~
hide.c: In function ‘request_pwd’:
hide.c:165:38: error: ‘SCREEN_BYTES_SIZE’ undeclared (first use in this function                                                                                                                ); did you mean ‘_REENT_SIGNAL_SIZE’?
     char *sbuffer = sbuffer = malloc(SCREEN_BYTES_SIZE);
                                      ^~~~~~~~~~~~~~~~~
                                      _REENT_SIGNAL_SIZE
hide.c:165:38: note: each undeclared identifier is reported only once for each f                                                                                                                unction it appears in
In file included from /home/littl/Ndless/ndless-sdk/include/os.h:24:0,
                 from hide.c:3:
/home/littl/Ndless/ndless-sdk/include/libndls.h:163:95: error: expected ‘;’ befo                                                                                                                re ‘}’ token
  #define SCREEN_BASE_ADDRESS ({"SCREEN_BASE_ADDRESS got removed in favor of the                                                                                                                 lcd_blit API."})
                                                                                                                                                                                                               ^
hide.c:166:21: note: in expansion of macro ‘SCREEN_BASE_ADDRESS’
     memcpy(sbuffer, SCREEN_BASE_ADDRESS, SCREEN_BYTES_SIZE);
                     ^~~~~~~~~~~~~~~~~~~
/home/littl/Ndless/ndless-sdk/include/libndls.h:163:95: error: expected ‘;’ befo                                                                                                                re ‘}’ token
  #define SCREEN_BASE_ADDRESS ({"SCREEN_BASE_ADDRESS got removed in favor of the                                                                                                                 lcd_blit API."})
                                                                                                                                                                                                               ^
hide.c:178:16: note: in expansion of macro ‘SCREEN_BASE_ADDRESS’
         memcpy(SCREEN_BASE_ADDRESS, sbuffer, SCREEN_BYTES_SIZE);
                ^~~~~~~~~~~~~~~~~~~
hide.c: In function ‘main’:
hide.c:212:9: error: ‘is_cx’ undeclared (first use in this function); did you me                                                                                                                an ‘is_cm’?
     if (is_cx) lcd_incolor();
         ^~~~~
         is_cm
hide.c:212:16: warning: implicit declaration of function ‘lcd_incolor’; did you                                                                                                                 mean ‘lcd_init’? [-Wimplicit-function-declaration]
     if (is_cx) lcd_incolor();
                ^~~~~~~~~~~
                lcd_init
make: *** [Makefile:17: hide.o] Error 1

littl@robbobSalt ~/Ndless/ndless-sdk
$ make
nspire-gcc -O2 -Wall -W -marm -c hide.c
hide.c: In function ‘setPixel’:
hide.c:60:8: warning: implicit declaration of function ‘lcd_isincolor’ [-Wimplicit-fun                                                                                                          ction-declaration]
     if(lcd_isincolor()) {
        ^~~~~~~~~~~~~
hide.c: In function ‘request_pwd’:
hide.c:165:38: error: ‘SCREEN_BYTES_SIZE’ undeclared (first use in this function); did                                                                                                           you mean ‘_REENT_SIGNAL_SIZE’?
     char *sbuffer = sbuffer = malloc(SCREEN_BYTES_SIZE);
                                      ^~~~~~~~~~~~~~~~~
                                      _REENT_SIGNAL_SIZE
hide.c:165:38: note: each undeclared identifier is reported only once for each functio                                                                                                          n it appears in
hide.c: In function ‘main’:
hide.c:212:9: error: ‘is_cx’ undeclared (first use in this function); did you mean ‘is                                                                                                          _cm’?
     if (is_cx) lcd_incolor();
         ^~~~~
         is_cm
hide.c:212:16: warning: implicit declaration of function ‘lcd_incolor’; did you mean                                                                                                            lcd_init’? [-Wimplicit-function-declaration]
     if (is_cx) lcd_incolor();
                ^~~~~~~~~~~
                lcd_init
make: *** [Makefile:17: hide.o] Error 1
`

**Comment by Vogtinator** [comment]
@GitHubQuestionAsker The Makefile you're using is too old and will not work with this sdk. Use `nspire-tools new hide` to generate a new one.

You'll have to either add `-D OLD_SCREEN_API` to `GCCFLAGS` or port the program to use [the new API](https://hackspire.org/index.php/Libndls#LCD_API).
